#!/usr/bin/env bash

# Check if git is available
if ! command -v 'git' >/dev/null; then
  echo 'Ooops, git not found.'
  exit 1
fi

# Define repository variables
local_repo="${HOME}/.git-oh-my"
remote_repo='https://github.com/adrfer/git-oh-my.git'

# Save git credentials, if any
name="$(git config user.name)"
email="$(git config user.email)"

# Backup existing files, if any
if [[ -d "${local_repo}" ]]; then
  echo -n 'Backing up existing git files...'
  mv -f "${local_repo%/}"{," copy $(date +%s)"}
  echo ' done.'
fi

# Download new files
echo -n 'Downloading some quick and dirty git files...'

if git clone "${remote_repo}" "${local_repo}" >/dev/null 2>&1; then
  echo ' done.'
else
  echo
  echo "Ooops, unable to access ${remote_repo}, try again."
  exit 1
fi

ln -sf "${local_repo}/gitconfig" "${HOME}/.gitconfig"
ln -sf "${local_repo}/gitignore" "${HOME}/.gitignore"
ln -sf "${local_repo}/gitmessage" "${HOME}/.gitmessage"

# Setup git credentials
echo 'Now, setting up your credentials...'

name_prompt='Your name: '

if [[ -n "${name}" ]]; then
  echo -n "Last configured name is ${name}. "
  read -r -p 'Keep it (y/n [n])? '

  if [[ ! "${REPLY}" =~ ^[Yy]$ ]]; then
    read -r -p "${name_prompt}" name
  fi
else
  read -r -p "${name_prompt}" name
fi

git config --global user.name "${name}"

email_prompt='Your email: '

if [[ -n "${email}" ]]; then
  echo -n "Last configured email is ${email}. "
  read -r -p 'Keep it (y/n [n])? '

  if [[ ! "${REPLY}" =~ ^[Yy]$ ]]; then
    read -r -p "${email_prompt}" email
  fi
else
  read -r -p "${email_prompt}" email
fi

git config --global user.email "${email}"

echo 'All good, enjoy!'
exit 0
