#!/usr/bin/env bash

# Confirm uninstall
read -r -p 'Sure to uninstall (y/n [n])? '

if [[ ! "${REPLY}" =~ ^[Yy]$ ]]; then
  echo 'Ok then, nothing much to see here.'
  exit 0
fi

# Define repository variable
local_repo="${HOME}/.git-oh-my"

# Remove local files, if any
if [[ -d "${local_repo}" ]]; then
  echo -n "Removing ${local_repo}..."
  rm -rf "${local_repo}"
  echo ' done.'
else
  echo "${local_repo} not found."
fi

# Define configuration variables
local_gitconfig="${HOME}/.gitconfig"
local_gitignore="${HOME}/.gitignore"

# Remove symlinks, if any
files=( "${local_gitconfig}" "${local_gitignore}" )

for file in "${files[@]}"; do
  if [[ -L "${file}" ]]; then
    echo -n "Removing ${file}..."
    rm -f "${file}"
    echo ' done.'
  else
    echo "${file} not found."
  fi
done

# Backup local files, if any
read -r -p "Check for ${local_repo} backups? (y/n [n])? "

if [[ ! "${REPLY}" =~ ^[Yy]$ ]]; then
  echo 'Ok then, good to go!'
  exit 0
fi

local_repo_backup_pattern='.git-oh-my copy*'
local_repo_backup=$(find "${HOME}" -maxdepth 1 -type d -name "${local_repo_backup_pattern}" | sort -r | head -n1)

if [[ -n "${local_repo_backup}" ]]; then
  read -r -p "Last backup is ${local_repo_backup}. Restore it (y/n [n])? "

  if [[ "${REPLY}" =~ ^[Yy]$ ]]; then
    echo -n "Restoring ${local_repo_backup}..."
    mv -f "${local_repo_backup}" "${local_repo}"
    echo ' done.'
  fi
else
  echo "No backups found for ${local_repo}."
fi

echo 'All good, farewell!'
exit 0
